import React from "react";
import { ServicePage } from "../components/ui/service-page";

export function AIAutomationPage({ lang = "es" }: { lang?: string }) {
  const content = {
    es: {
      serviceName: "Automatización IA",
      tagline: "Agentes Inteligentes\nque Trabajan por Ti",
      description:
        "Diseñamos ecosistemas de agentes de IA que automatizan procesos críticos, toman decisiones autónomas y escalan operaciones sin límites humanos.",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1677442136019-21780ecad995?w=1600&q=80",
          subheading: "Multi-Agente",
          heading: "Orquestación Autónoma",
          bodyTitle: "Sistemas que piensan y actúan",
          bodyText1:
            "Nuestros agentes multi-modelo coordinan tareas complejas entre departamentos: ventas, soporte, operaciones y analítica, sin intervención humana.",
          bodyText2:
            "Integramos modelos GPT-4, Claude y Gemini con tus sistemas existentes para crear un cerebro operativo que trabaja 24/7.",
          ctaLabel: "Ver Demo",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1620712943543-bcc4688e7485?w=1600&q=80",
          subheading: "RAG & Memoria",
          heading: "IA con Contexto Empresarial",
          bodyTitle: "Tu empresa como base de conocimiento",
          bodyText1:
            "Implementamos sistemas RAG (Retrieval-Augmented Generation) que convierten tu documentación, CRM y datos históricos en el contexto que necesita tu IA.",
          bodyText2:
            "El resultado: respuestas precisas, relevantes y adaptadas a tu industria, no respuestas genéricas de un LLM base.",
          ctaLabel: "Conocer más",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1677442135703-1787eea5ce01?w=1600&q=80",
          subheading: "Automatización",
          heading: "ROI desde el Día 1",
          bodyTitle: "Resultados medibles, no promesas",
          bodyText1:
            "Cada implementación de IA include métricas de impacto: horas ahorradas, costos reducidos, errores eliminados. Nuestros clientes reportan 60-80% de reducción en tareas repetitivas.",
          bodyText2:
            "Comenzamos con un piloto de 30 días para validar el valor antes de escalar en toda la organización.",
          ctaLabel: "Iniciar Piloto",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1589254065878-42c9da997008?w=1600&q=80",
          subheading: "Voz & Conversación",
          heading: "Agentes de Voz IA",
          bodyTitle: "Comunicación natural 24/7",
          bodyText1: "Implementamos sistemas de voz inteligentes que manejan llamadas entrantes y salientes con lenguaje natural, resolviendo hasta el 70% de las consultas sin agentes humanos.",
          bodyText2: "Integración directa con tu centralita o sistemas cloud para una experiencia telefónica fluida y sin esperas.",
          ctaLabel: "Escuchar Demo",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1527430253228-e903f48ea317?w=1600&q=80",
          subheading: "Vision",
          heading: "Computer Vision & OCR",
          bodyTitle: "Tu IA ahora puede ver",
          bodyText1: "Automatizamos el procesamiento de documentos, facturas y vigilancia mediante modelos de visión por computadora que extraen datos con una precisión del 99.9%.",
          bodyText2: "Ahorra miles de horas en entrada de datos manual y procesamiento de formularios complejos.",
          ctaLabel: "Ver Casos",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1551288049-bbdac8626ad1?w=1600&q=80",
          subheading: "Analítica",
          heading: "Modelos Predictivos",
          bodyTitle: "Anticipa el futuro de tu negocio",
          bodyText1: "Desarrollamos modelos de forecasting que predicen la demanda, el churn de clientes y anomalías en tus operaciones basándose en datos históricos.",
          bodyText2: "Toma decisiones basadas en proyecciones matemáticas, no en suposiciones.",
          ctaLabel: "Analizar Datos",
        },
      ],
    },
    en: {
      serviceName: "AI Automation",
      tagline: "Intelligent Agents\nWorking for You",
      description:
        "We design AI agent ecosystems that automate critical processes, make autonomous decisions, and scale operations beyond human limits.",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1677442136019-21780ecad995?w=1600&q=80",
          subheading: "Multi-Agent",
          heading: "Autonomous Orchestration",
          bodyTitle: "Systems that think and act",
          bodyText1:
            "Our multi-model agents coordinate complex tasks across departments: sales, support, operations, and analytics — without human intervention.",
          bodyText2:
            "We integrate GPT-4, Claude, and Gemini models with your existing systems to create an operational brain that works 24/7.",
          ctaLabel: "See Demo",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1620712943543-bcc4688e7485?w=1600&q=80",
          subheading: "RAG & Memory",
          heading: "AI with Business Context",
          bodyTitle: "Your company as a knowledge base",
          bodyText1:
            "We implement RAG (Retrieval-Augmented Generation) systems that turn your documentation, CRM, and historical data into context your AI needs.",
          bodyText2:
            "The result: precise, relevant, industry-specific answers — not generic responses from a base LLM.",
          ctaLabel: "Learn More",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1677442135703-1787eea5ce01?w=1600&q=80",
          subheading: "Automation",
          heading: "ROI from Day 1",
          bodyTitle: "Measurable results, not promises",
          bodyText1:
            "Every AI implementation includes impact metrics: hours saved, costs reduced, errors eliminated. Our clients report 60-80% reduction in repetitive tasks.",
          bodyText2:
            "We start with a 30-day pilot to validate value before scaling across the entire organization.",
          ctaLabel: "Start Pilot",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1589254065878-42c9da997008?w=1600&q=80",
          subheading: "Voice & Talk",
          heading: "AI Voice Agents",
          bodyTitle: "Natural communication 24/7",
          bodyText1: "We implement intelligent voice systems that handle inbound and outbound calls with natural language, solving up to 70% of queries without human agents.",
          bodyText2: "Direct integration with your PBX or cloud systems for a fluid, wait-free phone experience.",
          ctaLabel: "Listen Demo",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1527430253228-e903f48ea317?w=1600&q=80",
          subheading: "Vision",
          heading: "Computer Vision & OCR",
          bodyTitle: "Your AI can now see",
          bodyText1: "We automate document processing, invoicing and surveillance using computer vision models that extract data with 99.9% accuracy.",
          bodyText2: "Save thousands of hours in manual data entry and complex form processing.",
          ctaLabel: "View Cases",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1551288049-bbdac8626ad1?w=1600&q=80",
          subheading: "Analytics",
          heading: "Predictive Models",
          bodyTitle: "Anticipate your business future",
          bodyText1: "We develop forecasting models that predict demand, customer churn and operational anomalies based on historical data.",
          bodyText2: "Make decisions based on mathematical projections, not assumptions.",
          ctaLabel: "Analyze Data",
        },
      ],
    },


    zh: {
      serviceName: "人工智能自動化",
      tagline: "為你工作的\n智能代理",
      description: "我們設計人工智能代理解決方案，自動化關鍵流程，自主做出決策，並無限制地擴展運營。",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1677442136019-21780ecad995?w=1600&q=80",
          subheading: "多代理",
          heading: "自主協調",
          bodyTitle: "思考並行動的系統",
          bodyText1: "我們的多模型代理協調跨部門的複雜任務：銷售、支援、營運和分析——無需人工干預。",
          bodyText2: "我們將 GPT-4、Claude 和 Gemini 模型與您現有的系統整合，創造一個全天候運作的營運大腦。",
          ctaLabel: "查看示範",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1620712943543-bcc4688e7485?w=1600&q=80",
          subheading: "RAG與記憶",
          heading: "具備業務背景的AI",
          bodyTitle: "您的公司作為知識庫",
          bodyText1: "我們實施 RAG 系統，將您的文件、CRM 和歷史數據轉化為 AI 所需的背景資訊。",
          bodyText2: "結果是：準確、相關、特定行業的答案——而不是基礎大語言模型的通用回答。",
          ctaLabel: "了解更多",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1677442135703-1787eea5ce01?w=1600&q=80",
          subheading: "自動化",
          heading: "從第一天獲得投資回報",
          bodyTitle: "可衡量的結果，而非承諾",
          bodyText1: "每個 AI 佈署都包含影響力指標：節省的時間、降低的成本、消除的錯誤。我們的客戶報告指出重複性任務減少了 60-80%。",
          bodyText2: "我們從 30 天的試驗開始，以驗證價值，然後再擴展到整個組織。",
          ctaLabel: "開始試驗",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1589254065878-42c9da997008?w=1600&q=80",
          subheading: "語音與對話",
          heading: "AI 語音代理",
          bodyTitle: "全天候自然對話",
          bodyText1: "我們實施智能語音系統，以自然語言處理來電和外呼，在沒有人工客服的協助下解決高達 70% 的查詢。",
          bodyText2: "直接與您的 PBX 或雲端系統整合，提供流暢、無需等待的電話體驗。",
          ctaLabel: "聆聽示範",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1527430253228-e903f48ea317?w=1600&q=80",
          subheading: "視覺",
          heading: "計算機視覺與 OCR",
          bodyTitle: "您的 AI 現在可以看到",
          bodyText1: "我們使用計算機視覺模型自動化文件處理、發票和監控，以 99.9% 的準確率提取數據。",
          bodyText2: "在人工數據輸入和複雜表單處理中節省數千小時。",
          ctaLabel: "查看案例",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1551288049-bbdac8626ad1?w=1600&q=80",
          subheading: "分析",
          heading: "預測模型",
          bodyTitle: "預見您的業務未來",
          bodyText1: "我們開發預測模型，基於歷史數據預測需求、客戶流失和營運異常。",
          bodyText2: "根據數學預測而非假設做出決策。",
          ctaLabel: "分析數據",
        },
      ],
    },
    ru: {
      serviceName: "ИИ Автоматизация",
      tagline: "Интеллектуальные агенты\nработают на вас",
      description: "Мы проектируем экосистемы агентов ИИ, автоматизирующих критически важные процессы.",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1677442136019-21780ecad995?w=1600&q=80",
          subheading: "Мульти-агентный",
          heading: "Автономная оркестровка",
          bodyTitle: "Системы, которые думают и действуют",
          bodyText1: "Наши мультимодальные агенты координируют сложные задачи без участия человека.",
          bodyText2: "Мы интегрируем GPT-4, Claude и Gemini в операционный мозг 24/7.",
          ctaLabel: "Смотреть демо",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1620712943543-bcc4688e7485?w=1600&q=80",
          subheading: "RAG и Память",
          heading: "ИИ с контекстом бизнеса",
          bodyTitle: "Ваша компания как база знаний",
          bodyText1: "Внедряем системы RAG, превращающие ваши данные в контекст.",
          bodyText2: "Точные, релевантные ответы вместо шаблонов LLM.",
          ctaLabel: "Узнать больше",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1677442135703-1787eea5ce01?w=1600&q=80",
          subheading: "Автоматизация",
          heading: "Окупаемость с первого дня",
          bodyTitle: "Измеримые результаты",
          bodyText1: "Внедрение экономит время и ресурсы, снижая рутину на 60-80%.",
          bodyText2: "От пилота на 30 дней до масштабирования.",
          ctaLabel: "Начать проект",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1589254065878-42c9da997008?w=1600&q=80",
          subheading: "Голос и Чат",
          heading: "Голосовые ИИ-агенты",
          bodyTitle: "Связь 24/7",
          bodyText1: "Интеллектуальные аудиосистемы решают 70% обращений.",
          bodyText2: "Интеграция с АТС без ожидания на линии.",
          ctaLabel: "Слушать демо",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1527430253228-e903f48ea317?w=1600&q=80",
          subheading: "Зрение",
          heading: "Компьютерное зрение и OCR",
          bodyTitle: "Ваш ИИ умеет видеть",
          bodyText1: "Точность извлечения данных из документов 99.9%.",
          bodyText2: "Секреты автоматизации экономят тысячи часов.",
          ctaLabel: "Модели",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1551288049-bbdac8626ad1?w=1600&q=80",
          subheading: "Анализ",
          heading: "Предиктивные модели",
          bodyTitle: "Прогнозируйте будущее",
          bodyText1: "Модели могут прогнозировать спрос на основе данных.",
          bodyText2: "Решения, основанные на математике.",
          ctaLabel: "Анализ",
        },
      ],
    },
    pt: {
      serviceName: "Automação IA",
      tagline: "Agentes Inteligentes\nTrabalhando por Você",
      description: "Projetamos ecossistemas de agentes de IA.",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1677442136019-21780ecad995?w=1600&q=80",
          subheading: "Multi-Agente",
          heading: "Orquestração Autônoma",
          bodyTitle: "Sistemas que pensam e agem",
          bodyText1: "Coordenam tarefas sem intervenção humana.",
          bodyText2: "Integramos GPT-4 num cérebro 24/7.",
          ctaLabel: "Ver Demo",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1620712943543-bcc4688e7485?w=1600&q=80",
          subheading: "RAG & Memória",
          heading: "IA com Contexto",
          bodyTitle: "Sua empresa como base de dados",
          bodyText1: "Convertemos o CRM em contexto.",
          bodyText2: "Resultados da IA adaptados à indústria.",
          ctaLabel: "Mais",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1677442135703-1787eea5ce01?w=1600&q=80",
          subheading: "Automação",
          heading: "ROI do Dia 1",
          bodyTitle: "Resultados reais",
          bodyText1: "A implementação reduz tarefas repetitivas.",
          bodyText2: "Prova piloto grátis.",
          ctaLabel: "Piloto",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1589254065878-42c9da997008?w=1600&q=80",
          subheading: "Voz",
          heading: "Voz de IA",
          bodyTitle: "Interações naturais",
          bodyText1: "As respostas podem ser fluídas sem operadores humanos.",
          bodyText2: "Integração PABX nas nuvens.",
          ctaLabel: "Escutar",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1527430253228-e903f48ea317?w=1600&q=80",
          subheading: "Visão",
          heading: "Visão de Computador",
          bodyTitle: "Extrção dos papéis",
          bodyText1: "Extraímos dados com 99,99%.",
          bodyText2: "Extração sem digitações errôneas.",
          ctaLabel: "Ver as Fontes",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1551288049-bbdac8626ad1?w=1600&q=80",
          subheading: "Análises",
          heading: "Modelos Preditivos",
          bodyTitle: "Antecipe sua necessidade",
          bodyText1: "Forneça preditores com facilidade.",
          bodyText2: "Previsões em tempo hábil.",
          ctaLabel: "Projetar os Dados",
        },
      ],
    },
  }[lang as 'es'|'en'|'zh'|'ru'|'pt'] || { serviceName: 'Loading', tagline: 'Loading', description: 'Loading...', sections: [] };

  return <ServicePage {...content} serviceSlug="ai-automation" lang={lang} />;
}

export function ImmersiveWebsPage({ lang = "es" }: { lang?: string }) {
  const content = {
    es: {
      serviceName: "Webs Inmersivas",
      tagline: "Experiencias Digitales\nque Impactan",
      description:
        "Construimos interfaces de nueva generación que combinan animación avanzada, 3D interactivo y UX premium para marcas que quieren destacar.",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1639762681485-074b7f938ba0?w=1600&q=80",
          subheading: "WebGL & 3D",
          heading: "Más allá del Píxel",
          bodyTitle: "Entornos tridimensionales en el navegador",
          bodyText1:
            "Usamos Three.js, React Three Fiber y WebGL para crear experiencias 3D interactivas que corren directamente en el navegador, sin plugins.",
          bodyText2:
            "Desde showrooms de productos hasta portfolios inmersivos: llevamos tu marca a la tercera dimensión.",
          ctaLabel: "Ver Proyectos",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1550751827-4bd374c3f58b?w=1600&q=80",
          subheading: "Animación",
          heading: "Microinteracciones Premium",
          bodyTitle: "Cada pixel tiene propósito",
          bodyText1:
            "GSAP, Framer Motion y Lenis smooth scroll se combinan para crear transiciones cinematográficas que guían al usuario con fluidez y precisión.",
          bodyText2:
            "El resultado es una interfaz que no solo funciona bien, sino que se siente etérea y memorable.",
          ctaLabel: "Ver Demo",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1614850523459-c2f4c699c52e?w=1600&q=80",
          subheading: "Performance",
          heading: "Velocidad sin Compromiso",
          bodyTitle: "Belleza y velocidad coexisten",
          bodyText1:
            "Optimizamos cada componente para lograr Core Web Vitals perfectos: LCP < 2.5s, CLS < 0.1, FID < 100ms. La velocidad no es negociable.",
          bodyText2:
            "Nuestras webs inmersivas cargan en <2s y mantienen 60fps incluso con efectos visuales complejos.",
          ctaLabel: "Iniciar Proyecto",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1633356122544-f134324a6cee?w=1600&q=80",
          subheading: "Realidad Mixta",
          heading: "WebAR Integrada",
          bodyTitle: "El mundo real como lienzo",
          bodyText1: "Llevamos tus productos al espacio físico de tus clientes mediante Realidad Aumentada que corre directamente en el navegador móvil, sin descargar apps.",
          bodyText2: "Aumenta la tasa de conversión permitiendo que los usuarios visualicen productos en su propio entorno.",
          ctaLabel: "Probar AR",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1617839659905-2079d9465cc0?w=1600&q=80",
          subheading: "Inmersión",
          heading: "Showrooms 360",
          bodyTitle: "Visitas virtuales de alta fidelidad",
          bodyText1: "Creamos gemelos digitales y recorridos virtuales interactivos que permiten explorar instalaciones o productos con una calidad visual cinematográfica.",
          bodyText2: "Navegación intuitiva y puntos de interacción inteligentes para una experiencia de venta inmersiva.",
          ctaLabel: "Entrar",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1550684848-fac1c5b4e853?w=1600&q=80",
          subheading: "Visuals",
          heading: "Shader Art & FX",
          bodyTitle: "Estética digital de vanguardia",
          bodyText1: "Desarrollamos efectos visuales personalizados mediante GLSL Shaders que reaccionan a la música, al scroll o al movimiento del ratón.",
          bodyText2: "Distinción visual absoluta que posiciona a tu marca en el top tier de la innovación tecnológica.",
          ctaLabel: "Ver Efectos",
        },
      ],
    },
    en: {
      serviceName: "Immersive Webs",
      tagline: "Digital Experiences\nthat Impact",
      description:
        "We build next-generation interfaces combining advanced animation, interactive 3D, and premium UX for brands that want to stand out.",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1639762681485-074b7f938ba0?w=1600&q=80",
          subheading: "WebGL & 3D",
          heading: "Beyond the Pixel",
          bodyTitle: "Three-dimensional environments in the browser",
          bodyText1:
            "We use Three.js, React Three Fiber and WebGL to create interactive 3D experiences that run directly in the browser, no plugins needed.",
          bodyText2:
            "From product showrooms to immersive portfolios: we take your brand into the third dimension.",
          ctaLabel: "See Projects",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1550751827-4bd374c3f58b?w=1600&q=80",
          subheading: "Animation",
          heading: "Premium Microinteractions",
          bodyTitle: "Every pixel has purpose",
          bodyText1:
            "GSAP, Framer Motion and Lenis smooth scroll combine to create cinematic transitions that guide users with fluidity and precision.",
          bodyText2:
            "The result is an interface that not only works well, but feels ethereal and memorable.",
          ctaLabel: "See Demo",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1614850523459-c2f4c699c52e?w=1600&q=80",
          subheading: "Performance",
          heading: "Speed Without Compromise",
          bodyTitle: "Beauty and speed coexist",
          bodyText1:
            "We optimize every component for perfect Core Web Vitals: LCP < 2.5s, CLS < 0.1, FID < 100ms. Speed is non-negotiable.",
          bodyText2:
            "Our immersive webs load in <2s and maintain 60fps even with complex visual effects.",
          ctaLabel: "Start Project",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1633356122544-f134324a6cee?w=1600&q=80",
          subheading: "Mixed Reality",
          heading: "Integrated WebAR",
          bodyTitle: "The real world as a canvas",
          bodyText1: "We bring your products into your customers' physical space through Augmented Reality that runs directly in the mobile browser, without downloading apps.",
          bodyText2: "Increase conversion rates by allowing users to visualize products in their own environment.",
          ctaLabel: "Try AR",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1617839659905-2079d9465cc0?w=1600&q=80",
          subheading: "Immersion",
          heading: "360 Showrooms",
          bodyTitle: "High-fidelity virtual tours",
          bodyText1: "We create digital twins and interactive virtual tours that allow exploring facilities or products with cinematic visual quality.",
          bodyText2: "Intuitive navigation and smart interaction points for an immersive sales experience.",
          ctaLabel: "Enter",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1550684848-fac1c5b4e853?w=1600&q=80",
          subheading: "Visuals",
          heading: "Shader Art & FX",
          bodyTitle: "Vanguard digital aesthetics",
          bodyText1: "We develop custom visual effects using GLSL Shaders that react to music, scroll, or mouse movement.",
          bodyText2: "Absolute visual distinction that positions your brand at the top tier of technological innovation.",
          ctaLabel: "See Effects",
        },
      ],
    },


    zh: {
      serviceName: "沉浸式網站",
      tagline: "有影響力\n的數位體驗",
      description: "為希望突破框架的品牌而設計。",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1639762681485-074b7f938ba0?w=1600&q=80",
          subheading: "WebGL 與 3D",
          heading: "超越像素",
          bodyTitle: "三維空間",
          bodyText1: "基於 Three.js 驅動瀏覽器3D界面。",
          bodyText2: "使產品展示廳升到三維層次。",
          ctaLabel: "專案展示",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1550751827-4bd374c3f58b?w=1600&q=80",
          subheading: "動畫效果",
          heading: "細微互動",
          bodyTitle: "每個區塊均有玄機",
          bodyText1: "GSAP 流暢切換",
          bodyText2: "具有電影感覺的頁面。",
          ctaLabel: "示範",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1614850523459-c2f4c699c52e?w=1600&q=80",
          subheading: "系統效能",
          heading: "極速響應效能",
          bodyTitle: "美感與速度兼具",
          bodyText1: "完美支援LCP。",
          bodyText2: "載入無須等待即可執行60fps複雜畫面。",
          ctaLabel: "進行開發",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1633356122544-f134324a6cee?w=1600&q=80",
          subheading: "混合現實",
          heading: "整合的 WebAR",
          bodyTitle: "與現實相遇",
          bodyText1: "不需要開發原生APP即支援手機實體實境。",
          bodyText2: "加強購買下訂成功機率。",
          ctaLabel: "馬上嘗試",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1617839659905-2079d9465cc0?w=1600&q=80",
          subheading: "沉浸式空間",
          heading: "全場景360度展示廳",
          bodyTitle: "高品質導覽解說",
          bodyText1: "製作您的數位分身，引導客戶線上解說產品。",
          bodyText2: "自動生成的智能銷售系統。",
          ctaLabel: "進入",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1550684848-fac1c5b4e853?w=1600&q=80",
          subheading: "頂尖美學",
          heading: "數位技術前沿",
          bodyTitle: "視覺互動震撼",
          bodyText1: "自定GLSL渲染效果並進行各種觸發互動",
          bodyText2: "將您的企業帶向領先者的視覺維度",
          ctaLabel: "前往欣賞",
        },
      ],
    },
    ru: {
      serviceName: "Иммерсивные Веб-сайты",
      tagline: "Цифровой опыт,\nкоторый впечатляет",
      description: "Мы создаем интерфейсы нового поколения.",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1639762681485-074b7f938ba0?w=1600&q=80",
          subheading: "WebGL & 3D",
          heading: "За пределами пикселя",
          bodyTitle: "Трехмерные среды",
          bodyText1: "Создаем интерактивные 3D-интерфейсы.",
          bodyText2: "Лучшие продукты в формате showroom.",
          ctaLabel: "Проекты",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1550751827-4bd374c3f58b?w=1600&q=80",
          subheading: "Анимация",
          heading: "Микроинтеракты",
          bodyTitle: "У каждого пикселя есть цель",
          bodyText1: "GSAP-переходы кинематографического качества.",
          bodyText2: "Идеальная адаптация.",
          ctaLabel: "Демо",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1614850523459-c2f4c699c52e?w=1600&q=80",
          subheading: "Сценарии",
          heading: "Производительность",
          bodyTitle: "Быстрый код",
          bodyText1: "Скорость без компромиссов LCP < 2c.",
          bodyText2: "Ожидание пользователей сведено к минимуму.",
          ctaLabel: "Запуск",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1633356122544-f134324a6cee?w=1600&q=80",
          subheading: "WebAR",
          heading: "Дополненная реальность",
          bodyTitle: "Ваш дом как холст",
          bodyText1: "Смотрите товары без скачивания APP.",
          bodyText2: "Коэффициент конверсии намного выше.",
          ctaLabel: "AR Просмотр",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1617839659905-2079d9465cc0?w=1600&q=80",
          subheading: "Эффект",
          heading: "Настройка в 360",
          bodyTitle: "Полноценные туры",
          bodyText1: "Шоурумы на базе VR и 3D.",
          bodyText2: "Объемный контент доступен по клику.",
          ctaLabel: "Зайти",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1550684848-fac1c5b4e853?w=1600&q=80",
          subheading: "Эффекты",
          heading: "Шейдеры",
          bodyTitle: "Фантастическая эстетика",
          bodyText1: "Применение GLSL-рендеров.",
          bodyText2: "Эксклюзивность вашего бренда защищена.",
          ctaLabel: "Смотреть",
        },
      ],
    },
    pt: {
      serviceName: "Webs Imersivas",
      tagline: "Experiências Digitais\nque Impactam",
      description: "Construímos interfaces de nova geração que combinam animação avançada.",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1639762681485-074b7f938ba0?w=1600&q=80",
          subheading: "WebGL & 3D",
          heading: "Além do Pixel",
          bodyTitle: "Ambientes Tridimensionais",
          bodyText1: "Three.js para cenários iterativos no navegador.",
          bodyText2: "Showrooms de escala tridimensional.",
          ctaLabel: "Projetos",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1550751827-4bd374c3f58b?w=1600&q=80",
          subheading: "Animação",
          heading: "Interfaces Cinematográficas",
          bodyTitle: "Propósito em Detalhes",
          bodyText1: "Framer Motion com extrema velocidade.",
          bodyText2: "Resultados surreais no navegador comum.",
          ctaLabel: "Demo",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1614850523459-c2f4c699c52e?w=1600&q=80",
          subheading: "Performance",
          heading: "Otimização Avançada",
          bodyTitle: "Redução de Latência",
          bodyText1: "O carregamento leva apenas alguns milissegundos nas tecnologias.",
          bodyText2: "Garantia de que você não perde oportunidades de vendas.",
          ctaLabel: "Iniciar",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1633356122544-f134324a6cee?w=1600&q=80",
          subheading: "AR na Mão",
          heading: "Sua Casa Conectada",
          bodyTitle: "Prova Rápida nos Espelhos.",
          bodyText1: "Sem baixar o APP da loja e convertendo de imediato.",
          bodyText2: "Facilitamos os trâmites do dia a dia pro usuário.",
          ctaLabel: "Pôr na Sala",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1617839659905-2079d9465cc0?w=1600&q=80",
          subheading: "Viagens Realísticas",
          heading: "Concessionária Aberta",
          bodyTitle: "Converse e Negocie",
          bodyText1: "Faça seu ambiente online de maneira incopiável pelas marcas.",
          bodyText2: "Gaste menos com a construção de lojas físicas grandes.",
          ctaLabel: "Vamos Lá",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1550684848-fac1c5b4e853?w=1600&q=80",
          subheading: "Arte Visual",
          heading: "GLSL Shader",
          bodyTitle: "Renderização com Gráficos",
          bodyText1: "Desenvolva interfaces fluidas baseadas na criatividade e no poder visual.",
          bodyText2: "Tenha a melhor página da web comparada com outros.",
          ctaLabel: "Tocar",
        },
      ],
    },
  }[lang as 'es'|'en'|'zh'|'ru'|'pt'] || { serviceName: 'Loading', tagline: 'Loading', description: 'Loading...', sections: [] };

  return <ServicePage {...content} serviceSlug="immersive-webs" lang={lang} />;
}

export function ModernizationPage({ lang = "es" }: { lang?: string }) {
  const content = {
    es: {
      serviceName: "Modernización",
      tagline: "Transmuta tu\nDeuda Técnica",
      description:
        "Convertimos sistemas legacy en arquitecturas modernas, escalables y rentables sin detener tus operaciones.",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1614850523296-d8c1af93d400?w=1600&q=80",
          subheading: "Migración",
          heading: "Legacy a Cloud-Native",
          bodyTitle: "Sin interrupción operativa",
          bodyText1:
            "Migramos monolitos a microservicios con estrategias de strangler fig y blue-green deployments que garantizan continuidad del negocio durante la transición.",
          bodyText2:
            "De COBOL, .NET Framework o Java 6 a arquitecturas modernas en AWS, GCP o Azure: lo hemos hecho antes y lo haremos de nuevo.",
          ctaLabel: "Evaluar mi Sistema",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1451187580459-43490279c0fa?w=1600&q=80",
          subheading: "Serverless",
          heading: "Costos que Escalan con Ti",
          bodyTitle: "Paga solo por lo que usas",
          bodyText1:
            "Rediseñamos tu infraestructura para aprovechar funciones serverless, containers y orquestación con Kubernetes, reduciendo costos hasta un 70%.",
          bodyText2:
            "Auto-scaling automático: tu sistema maneja picos de 10x sin configuración manual ni costos de sobreaprovisionamiento.",
          ctaLabel: "Calcular Ahorro",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1518770660439-4636190af475?w=1600&q=80",
          subheading: "DevOps",
          heading: "CI/CD desde el Día 0",
          bodyTitle: "Entregas continuas, calidad continua",
          bodyText1:
            "Implementamos pipelines de CI/CD con GitHub Actions, GitLab CI o Jenkins. Cada commit pasa por pruebas automáticas, análisis de seguridad y deployment.",
          bodyText2:
            "El tiempo de deployment pasa de semanas a minutos. La tasa de fallos en producción baja un promedio de 85%.",
          ctaLabel: "Ver Proceso",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1558494949-ef010cbdcc51?w=1600&q=80",
          subheading: "Refactoring",
          heading: "Modernización de APIs",
          bodyTitle: "Comunicación eficiente y escalable",
          bodyText1: "Transformamos interfaces REST legacy en arquitecturas modernas basadas en GraphQL o gRPC, mejorando el rendimiento y la flexibilidad de tus integraciones.",
          bodyText2: "Implementamos gateways de API y patrones de seguridad modernos para proteger tu capa de datos.",
          ctaLabel: "Ver Arquitectura",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1544383835-bda2bc66a55d?w=1600&q=80",
          subheading: "Data",
          heading: "Evolución de Bases de Datos",
          bodyTitle: "Tus datos a la velocidad del mañana",
          bodyText1: "Migramos bases de datos relacionales saturadas a soluciones NewSQL o NoSQL optimizadas para alto rendimiento y escalabilidad global.",
          bodyText2: "Estrategias de migración con zero-downtime para asegurar la integridad de tu activo más valioso.",
          ctaLabel: "Optimizar Datos",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1512941937669-90a1b58e7e9c?w=1600&q=80",
          subheading: "Mobile",
          heading: "Legacy a PWA / Híbrido",
          bodyTitle: "Presencia móvil sin fricciones",
          bodyText1: "Convertimos aplicaciones de escritorio o webs antiguas en PWAs modernas y aplicaciones móviles híbridas que ofrecen una experiencia nativa en Android e iOS.",
          bodyText2: "Aprovecha notificaciones push, modo offline y acceso al hardware del dispositivo.",
          ctaLabel: "Modernizar App",
        },
      ],
    },
    en: {
      serviceName: "Modernization",
      tagline: "Transmute Your\nTechnical Debt",
      description:
        "We convert legacy systems into modern, scalable, and profitable architectures without stopping your operations.",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1614850523296-d8c1af93d400?w=1600&q=80",
          subheading: "Migration",
          heading: "Legacy to Cloud-Native",
          bodyTitle: "Without operational interruption",
          bodyText1:
            "We migrate monoliths to microservices with strangler fig and blue-green deployment strategies that guarantee business continuity during the transition.",
          bodyText2:
            "From COBOL, .NET Framework or Java 6 to modern architectures on AWS, GCP or Azure: we've done it before and we'll do it again.",
          ctaLabel: "Evaluate My System",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1451187580459-43490279c0fa?w=1600&q=80",
          subheading: "Serverless",
          heading: "Costs that Scale with You",
          bodyTitle: "Pay only for what you use",
          bodyText1:
            "We redesign your infrastructure to leverage serverless functions, containers and Kubernetes orchestration, reducing costs up to 70%.",
          bodyText2:
            "Automatic auto-scaling: your system handles 10x traffic spikes without manual configuration or over-provisioning costs.",
          ctaLabel: "Calculate Savings",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1518770660439-4636190af475?w=1600&q=80",
          subheading: "DevOps",
          heading: "CI/CD from Day 0",
          bodyTitle: "Continuous delivery, continuous quality",
          bodyText1:
            "We implement CI/CD pipelines with GitHub Actions, GitLab CI or Jenkins. Every commit goes through automated testing, security analysis and deployment.",
          bodyText2:
            "Deployment time goes from weeks to minutes. Production failure rates drop by an average of 85%.",
          ctaLabel: "See Process",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1558494949-ef010cbdcc51?w=1600&q=80",
          subheading: "Refactoring",
          heading: "API Modernization",
          bodyTitle: "Efficient and scalable communication",
          bodyText1: "We transform legacy REST interfaces into modern GraphQL or gRPC based architectures, improving the performance and flexibility of your integrations.",
          bodyText2: "We implement API gateways and modern security patterns to protect your data layer.",
          ctaLabel: "See Architecture",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1544383835-bda2bc66a55d?w=1600&q=80",
          subheading: "Data",
          heading: "Database Evolution",
          bodyTitle: "Your data at the speed of tomorrow",
          bodyText1: "We migrate saturated relational databases to NewSQL or NoSQL solutions optimized for high performance and global scalability.",
          bodyText2: "Zero-downtime migration strategies to ensure the integrity of your most valuable asset.",
          ctaLabel: "Optimize Data",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1512941937669-90a1b58e7e9c?w=1600&q=80",
          subheading: "Mobile",
          heading: "Legacy to PWA / Hybrid",
          bodyTitle: "Frictionless mobile presence",
          bodyText1: "We convert desktop applications or old websites into modern PWAs and hybrid mobile apps that offer a native experience on Android and iOS.",
          bodyText2: "Leverage push notifications, offline mode and device hardware access.",
          ctaLabel: "Modernize App",
        },
      ],
    },


    zh: {
      serviceName: "現代化轉型",
      tagline: "轉換您的\n技術債",
      description: "將遺留系統轉化為可擴展架構。",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1614850523296-d8c1af93d400?w=1600&q=80",
          subheading: "遷移",
          heading: "Legacy 至 Cloud-Native",
          bodyTitle: "不中斷營運",
          bodyText1: "運用微服務策略轉型，轉移巨型程式。",
          bodyText2: "安全、不損失資料地轉往雲端。",
          ctaLabel: "立即諮詢",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1451187580459-43490279c0fa?w=1600&q=80",
          subheading: "自動擴展",
          heading: "控制伺服器開銷與節省成本",
          bodyTitle: "最佳性價比",
          bodyText1: "大幅下降不必要的資源，以降低系統損耗及成本浪費。",
          bodyText2: "面對任何促銷節日等不會崩潰系統的完美方案。",
          ctaLabel: "查看估價",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1518770660439-4636190af475?w=1600&q=80",
          subheading: "DevOps",
          heading: "基礎建設管道",
          bodyTitle: "流程的流暢度與維護度",
          bodyText1: "建置CICD流水線並以 GitHub 等管道建立程式碼稽核機制。",
          bodyText2: "避免重大過失進入部署的自動化處理方式。",
          ctaLabel: "探討研究",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1558494949-ef010cbdcc51?w=1600&q=80",
          subheading: "API及系統",
          heading: "建立資料溝通閘道",
          bodyTitle: "REST 現代化重構計畫",
          bodyText1: "引進新世代網頁技術包含最新的API協定來防護。",
          bodyText2: "強化伺服傳輸資料之安全性，不受漏洞所擾。",
          ctaLabel: "研究安全",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1544383835-bda2bc66a55d?w=1600&q=80",
          subheading: "資料演進",
          heading: "關聯與非關聯轉型",
          bodyTitle: "將資料發揮效應",
          bodyText1: "利用NoSQL及相關雲端存取技術打破資料庫死鎖",
          bodyText2: "保持穩定且提供未來資料模型拓展的可能性",
          ctaLabel: "建立架構",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1512941937669-90a1b58e7e9c?w=1600&q=80",
          subheading: "跨平台",
          heading: "Legacy至PWA或混合 App",
          bodyTitle: "突破手提設備的限制與體驗強化",
          bodyText1: "製作桌面系統轉移至手機行動及各類混合模式上的轉移工程。",
          bodyText2: "隨時離線存取支援及增加推送等客戶聯繫介面。",
          ctaLabel: "現代化轉換",
        },
      ],
    },
    ru: {
      serviceName: "Модернизация",
      tagline: "Свобода от\nтехнического долга",
      description: "Модернизация без прерывания работы — для быстрого бизнеса.",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1614850523296-d8c1af93d400?w=1600&q=80",
          subheading: "Миграция",
          heading: "Иммиграция к облаку",
          bodyTitle: "Без простоев в работе",
          bodyText1: "Создаем новые связи и микросервисы из старого ядра.",
          bodyText2: "Модернизация без рисков для вашей выручки и процессов.",
          ctaLabel: "Инспекция",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1451187580459-43490279c0fa?w=1600&q=80",
          subheading: "Автономика",
          heading: "Гибкая балансировка",
          bodyTitle: "Экономьте ресурсы",
          bodyText1: "Масштабирование во время пиковых нагрузок или трафика.",
          bodyText2: "Ваш платеж только за использование ресурсов без потерь.",
          ctaLabel: "Оценить стоимость",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1518770660439-4636190af475?w=1600&q=80",
          subheading: "DevOps",
          heading: "Внедрение CI/CD",
          bodyTitle: "Управление деплоем",
          bodyText1: "Пайплайны автоматически проверяют, строят и выпускают релизы.",
          bodyText2: "Релиз теперь занимает минуту, а не неделю.",
          ctaLabel: "Изучить",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1558494949-ef010cbdcc51?w=1600&q=80",
          subheading: "Рефакторинг",
          heading: "Обновление API",
          bodyTitle: "Разработка на базе GraphQL",
          bodyText1: "Применение современных стандартов с целью гибкости на всех устройствах.",
          bodyText2: "Гарантированная кибербезопасность от любых видов инъекций в ваши API системы.",
          ctaLabel: "Взглянуть",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1544383835-bda2bc66a55d?w=1600&q=80",
          subheading: "СУБД",
          heading: "Скорость БД",
          bodyTitle: "NoSQL и облачные технологии кластеров",
          bodyText1: "Широкий функционал БД без блокировок и обрывов на сервере.",
          bodyText2: "Использование NoSQL для быстрой и гибкой архитектуры в развитии.",
          ctaLabel: "Подробности",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1512941937669-90a1b58e7e9c?w=1600&q=80",
          subheading: "Мобильность",
          heading: "Создание PWA решений",
          bodyTitle: "Для смартфонов в кармане",
          bodyText1: "Плавное перерождение старой базы в гибридные приложения и PWA продукты.",
          bodyText2: "Позволяет бизнесу всегда оставаться онлайн на телефоне каждого пользователя.",
          ctaLabel: "Улучшить сейчас",
        },
      ],
    },
    pt: {
      serviceName: "Modernização",
      tagline: "Transmute a Sua\nDívida Técnica",
      description: "Convertemos sistemas legados em arquiteturas modernas sem parar a operação.",
      sections: [
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1614850523296-d8c1af93d400?w=1600&q=80",
          subheading: "Transição Cloud",
          heading: "Arquitetura Cloud-Native",
          bodyTitle: "Operação Imparável",
          bodyText1: "Transformamos os sistemas antigos sem causar perdas na produção.",
          bodyText2: "De mainframes COBOL até o Azure mais moderno que temos.",
          ctaLabel: "Consulte Migração",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1451187580459-43490279c0fa?w=1600&q=80",
          subheading: "Serverless",
          heading: "Pague pelo Acesso",
          bodyTitle: "Elasticidade Total em Tempo Real",
          bodyText1: "Nossos servidores escalam com seus acessos, promovendo 70% de desconto no custo.",
          bodyText2: "Sua campanha em Black Friday nunca ficará inativa nas nossas mãos.",
          ctaLabel: "Consulte Faturas",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1518770660439-4636190af475?w=1600&q=80",
          subheading: "DevOps Ágil",
          heading: "Automações CI e CD",
          bodyTitle: "Semanal para Mensal e Instantâneo",
          bodyText1: "Trabalhos complexos e morosos se transformarão em algo leve com a nossa automação.",
          bodyText2: "Sempre analisado e revisto pelo time em frações de segundos em pipelines seguros.",
          ctaLabel: "Sistemas em Ação",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1558494949-ef010cbdcc51?w=1600&q=80",
          subheading: "Reformulação Geral",
          heading: "APIs e Pontes Gráficas Modernas",
          bodyTitle: "O GraphQL trazendo poder a interface",
          bodyText1: "Conectividade robusta que garante menos trafego na infra e maior ganho na interface final do usuário.",
          bodyText2: "Conexões seguras entre as frentes.",
          ctaLabel: "Reformule Suas Peças",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1544383835-bda2bc66a55d?w=1600&q=80",
          subheading: "Re-banco",
          heading: "Reconstrução do Banco",
          bodyTitle: "Um novo folego sem travas ao SQL",
          bodyText1: "Adicionamos modelos incríveis de busca a sua empresa via arquiteturas desatadas não estruturadas.",
          bodyText2: "Diga não ao limite da base e suporte ilimitados dados no projeto.",
          ctaLabel: "Expandir Terabytes",
        },
        {
          imgUrl: "https://images.unsplash.com/p?auto=format,compress&fit=crop&w=800&q=70hoto-1512941937669-90a1b58e7e9c?w=1600&q=80",
          subheading: "Desktop a Mobile",
          heading: "Sua vida dentro de PWA App",
          bodyTitle: "Tenha a Web na Mão Pelo Cel",
          bodyText1: "Tenha recursos como Notificações Locais sem um sistema iOS e Android pesadíssimos.",
          bodyText2: "Mais fácil de migrar em uma única base de código nativo já construído e moldado.",
          ctaLabel: "Testar as Inovações",
        },
      ],
    },
  }[lang as 'es'|'en'|'zh'|'ru'|'pt'] || { serviceName: 'Loading', tagline: 'Loading', description: 'Loading...', sections: [] };

  return <ServicePage {...content} serviceSlug="modernization" lang={lang} />;
}
